feat(solana-swap): initial version v1
KomodoPlatform/satomic-swap pull request #1
Opened 2024-03-28 06:55 UTC by r2st

2024-03-29 09:04 UTC, laruh requested changes
Thanks a lot for this feature!

I have some notes and questions.

PS: please commit `Cargo.lock` file, so security team (and devs actually) can see the whole deps tree. and it helps to be sure that all contributors have same deps.

2024-03-29 09:04 UTC, laruh commented on src/etomic_swap.rs
Please rename file to `satomic_swap`

2024-03-29 09:04 UTC, laruh commented on Cargo.toml
> +name = "etomic-swap-solana"
here, could you use `satomic-swap-solana` name

2024-03-29 09:04 UTC, laruh commented on src/tests.rs
please fix clippy warnings in tests
![image](https://github.com/KomodoPlatform/satomic-swap/assets/52405288/7c3c5696-5db0-43e7-846c-e309f589c5ab)


You can execute `cargo clippy --all-targets -- -D warnings` command to see warnings in tests without running them

2024-03-29 09:04 UTC, laruh commented on src/etomic_swap.rs
> +        AtomicSwapInstruction::SLPTokenPayment {
I believe there is a typo and naming should be `SPLTokenPayment`

2024-03-29 09:04 UTC, laruh commented on src/tests.rs
> +    instruction::Instruction,
we can do this `instruction::{AccountMeta, Instruction},`

2024-03-29 09:04 UTC, laruh commented on src/etomic_swap.rs
> +                                                                            //let token_program_account = next_account_info(accounts_iter)?; // SPL Token program account
do you need such commented code lines?

2024-03-29 09:04 UTC, laruh commented on src/etomic_swap.rs
> +                                                                   // Ensure the account data has enough space
Please dont inline comments in such cases.
Better to have it above the code:
```rust
            // Ensure the account data has enough space
            if data.len() < payment_bytes.len() {
                msg!("Error: Account data buffer too small");
                return Err(ProgramError::AccountDataTooSmall);
            }
```

2024-03-29 09:04 UTC, laruh commented on README.md
> +https://docs.solanalabs.com/cli/install
Please add more details about dev env setup, so any user/contributor can build solana program. 
Also its always better to leave notes about contribution rules: format code, run clippy etc.
For example

## Setup Dev environment

1. Install rust
https://www.rust-lang.org/tools/install

2. Install Solana CLI v1.18.8
https://docs.solanalabs.com/cli/install
```shell
sh -c "$(curl -sSfL https://release.solana.com/v1.18.8/install)"
```
## Build the project

To compile shared object (the program binary .so) run the command
```shell
cargo build-bpf
```

## Contribution

Before uploading any changes, please make sure that the test suite passes locally before submitting a pull request with your changes.

```
cargo test 
```
Use [Clippy](https://github.com/rust-lang/rust-clippy) to avoid common mistakes and [rustfmt](https://github.com/rust-lang/rustfmt) to make code clear.

1. Format the code using rustfmt:
 ```shell
    cargo fmt
 ```
2. Make sure there are no warnings and errors. Run the Clippy:
 ```shell
    cargo clippy --all-targets -- -D warnings
 ```

2024-03-29 09:04 UTC, laruh commented on src/tests.rs
> +    );
Do you need this and the rest code part?

2024-04-02 15:42 UTC, shamardy reviewed
Thanks for the PR! First review iteration where the purpose is to make the code more readable to better review it in subsequent iterations.

2024-04-02 15:42 UTC, shamardy commented on src/satomic_swap.rs
> +            msg!("Processing Payment");
We should start removing these logs since they consume compute units and their purpose is debugging only.

2024-04-02 15:42 UTC, shamardy commented on src/satomic_swap.rs
> +            let _vault_seeds_data: &[&[u8]] = &[
Please remove unused vars such as this one

2024-04-02 15:42 UTC, shamardy commented on src/satomic_swap.rs
> +                system_program_account.clone(),
I don't think we need the `system_program_account` when using invoke_signed with transfer. For a transfer operation, the involved accounts are typically just the sender and receiver of the funds afaik.

2024-04-02 15:42 UTC, shamardy commented on src/satomic_swap.rs
> +            Ok(())
This code block and others can probably be broken down to smaller functions to make `process_instruction` more manageable/readable. E.g. we can have 3 functions `create_payment`, `create_account` and `transfer_funds` for this part and call them here instead. Please do similar refactors to other blocks, the 3 functions I suggested are just for show but maybe you can refactor this in a better way, it's up to you.

2024-04-03 08:00 UTC, r2st commented on src/etomic_swap.rs
done

2024-04-03 08:00 UTC, r2st commented on Cargo.toml
> +name = "etomic-swap-solana"
I am now using "satomic-swap" , I hope that should be fine.
done

2024-04-03 08:01 UTC, r2st commented on src/tests.rs
done

2024-04-03 08:01 UTC, r2st commented on src/etomic_swap.rs
> +        AtomicSwapInstruction::SLPTokenPayment {
done

2024-04-03 08:01 UTC, r2st commented on src/tests.rs
> +    instruction::Instruction,
done

2024-04-03 08:01 UTC, r2st commented on src/etomic_swap.rs
> +                                                                            //let token_program_account = next_account_info(accounts_iter)?; // SPL Token program account
cleaned.
done

2024-04-03 08:01 UTC, r2st commented on src/etomic_swap.rs
> +                                                                   // Ensure the account data has enough space
done

2024-04-03 08:02 UTC, r2st commented on README.md
> +https://docs.solanalabs.com/cli/install
done

2024-04-03 08:02 UTC, r2st commented on src/tests.rs
> +    );
cleaned.
done

2024-04-03 14:28 UTC, laruh requested changes
Thanks for the fixes, next iteration

2024-04-03 14:28 UTC, laruh commented on src/satomic_swap.rs
> +            assert!(system_program::check_id(system_program_account.key));
Dont panic in production code, propagate the error instead

2024-04-03 14:28 UTC, laruh commented on src/satomic_swap.rs
> +            }
Why do you need this inner scope? I dont have compilation errors moving this inner scope operations to the outer.

To improve readability and maintainability please break the code into smaller well named functions, like Omer suggested.

2024-06-06 12:36 UTC, shamardy commented
The latest commit does the following as stated by @mj-blockydevs 

> List of applied suggestions:
>
> Removed msg calls.
Removed unused variables. IMPORTANT: For now, I've left unused struct properties to avoid changing the communication interface with the program. My main goal was to apply all suggestions without touching the "tests.rs" file, to ensure the business logic behind the program remained unchanged.
Broke the code into smaller functions. I've not only moved them to separate functions but also placed the functions in a dedicated module for clarity. Let me know if you are okay with this decision.
Using invoke_signed without the system program account. Let me know if I understood this particular requirement correctly.
Replaced panicking asserts with supported Solana Errors. Let me know if the ones I used are okay for you.
Removed inner scopes where they were not necessary.
Do you want me to prepare unit tests for the functions moved to the /utils directory, or are the already prepared tests sufficient for us at this stage?

@mj-blockydevs @laruh let's continue the review here since @mj-blockydevs now has access to the repo.

2024-06-06 12:51 UTC, shamardy commented
> Removed unused variables. IMPORTANT: For now, I've left unused struct properties to avoid changing the communication interface with the program. My main goal was to apply all suggestions without touching the "tests.rs" file, to ensure the business logic behind the program remained unchanged.

Will cover it in next review if there are any problems.

> I've not only moved them to separate functions but also placed the functions in a dedicated module for clarity. Let me know if you are okay with this decision.

Code looks much better this way, thanks for this refactor.

> Using invoke_signed without the system program account. Let me know if I understood this particular requirement correctly.

Looks good on first look, will check it extensively in the next review iteration.

> Replaced panicking asserts with supported Solana Errors. Let me know if the ones I used are okay for you.

Will check them case by case in the review.

> Do you want me to prepare unit tests for the functions moved to the /utils directory, or are the already prepared tests sufficient for us at this stage?

Unit tests for each module would be great to have but not necessary at this stage, it's up to you if you want to add them if there are no other higher priority items to finish first.

2024-06-06 13:55 UTC, shamardy reviewed
Thanks you for the fixes! Next review iteration!

2024-06-06 13:55 UTC, shamardy commented on Cargo.toml
it would be good to use latest versions of these crates, latest versions were used before but as you can see, the PR is 3 months old and newer versions were released.

2024-06-06 13:55 UTC, shamardy commented on Cargo.toml
> +[profile.release]
There can be a few changes that could potentially make the program more lightweight when deployed:

1. **`lto`**: This can be set to `"fat"` for aggressive Link Time Optimization (LTO). This is a good choice when compile time and memory usage during compilation are not important factors, as it can result in more efficient code.

2. **`codegen-units`**: Setting this to `1` can sometimes improve performance at the cost of longer compile times. This is a good choice for a Solana program.

3. **`panic`**: Setting this to `"abort"` can result in smaller binary size and faster program speed.

4. **`overflow-checks`**: This controls whether arithmetic operations are checked for overflow. In release mode, these checks are typically disabled for maximum performance. However, we should enable this option for security purposes.

5. **`opt-level`**: This controls the level of optimization. We should set this to `3` in the `build-override` section, which optimizes for speed. `opt-level = "z"` optimizes for size, as smaller programs are cheaper to deploy on the blockchain but we look for runtime optimization to optimize gas usage so using `3` would be better.

6. **`incremental`**: Set this to `false` to disable incremental compilation, which can reduce the size of the binary.

Here's a suggested `Cargo.toml` configuration:

```toml
[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = true

[profile.release.build-override]
opt-level = "3"
incremental = false
codegen-units = 1
```
These were taken from a popular solana program https://github.com/jup-ag/sol-swap-cpi/blob/main/Cargo.toml , you can check other popular solana program implementation for more inspirations on how to optimize the release profile for solana programs.

2024-06-06 13:55 UTC, shamardy commented on Cargo.toml
> +[profile.release]
c.c. @onur-ozkan would be great if I can get your feedback on this :)

2024-06-06 13:55 UTC, shamardy commented on README.md
> +### Install Solana CLI v1.18.8
We should remove the version from this title since we will be updating it periodically. We can add a note for the user to look at the cargo.toml to install the right version.

2024-06-06 13:55 UTC, shamardy commented on README.md
> +sh -c "$(curl -sSfL https://release.solana.com/v1.18.8/install)"
Same here with the version

2024-06-06 13:55 UTC, shamardy commented on src/instruction.rs
> +    pub fn unpack(
We should look into using `borsh` crate for serialization and deserialization instead of pack/unpack, maybe it will provide better performance but if not and the performance difference is negligible, using borsh will lead to less errors. This is not required in this PR but we should look into it in the future when completing the swap program for v1 and v2 swaps.

2024-06-06 13:55 UTC, shamardy commented on src/satomic_swap.rs
> +
I guess we need to transfer the tokens here.

2024-06-06 13:55 UTC, shamardy commented on src/satomic_swap.rs
> +            transfer_lamports(vault_pda, receiver_account, vault_seeds, amount)?;
We need also to add the case of tokens transfer here

2024-06-06 13:55 UTC, shamardy commented on src/satomic_swap.rs
> +            transfer_lamports(vault_pda, sender_account, vault_seeds, amount)?;
Same here.

2024-06-07 05:28 UTC, laruh requested changes
Great, here are notes from my side

2024-06-07 05:28 UTC, laruh commented on src/utils/payment.rs
> +};
I suppose there is a lack of `spl_token` crate usage to provide `transfer_spl_tokens` implementation

2024-06-07 05:28 UTC, laruh commented on Cargo.toml
> +spl-token = "4.0.0"
The `spl-token` crate was initially added under `[dev-dependencies]` but was not used in any test-specific code. Since it is required for the main program logic (for spl tokens instructions), it should be moved to `[dependencies]`.

2024-06-07 05:28 UTC, laruh commented on Cargo.toml
> +hex = { version = "0.4.3", features = [] }
Hmmm, I could run tests without these dependencies and I don't see their usage. They are redundant (for now)

2024-06-07 05:28 UTC, laruh commented on src/utils/hash.rs
> +    hasher.hash(&amount_bytes);
I think avoiding redundant small variables and using match pattern  make code clearer
```rust
    match token_program {
        Some(program) => hasher.hash(program.as_ref()),
        None => hasher.hash(&Pubkey::new_from_array([0; 32]).to_bytes()),
    }
    hasher.hash(&amount.to_le_bytes());
```

2024-06-07 05:33 UTC, onur-ozkan commented on Cargo.toml
> +[profile.release]
I don't know enough about the context of this project, so I don't know the trade-offs. But the dev/release options from https://github.com/KomodoPlatform/komodo-defi-framework/blob/b0fd99e8406e67ea06435dd028991caa5f522b5c/Cargo.toml#L54-L73 are generally good for most projects. It keeps the debug builds as fast as possible with least optimization and opposite on release ones.

2024-06-11 12:07 UTC, mj-blockydevs commented on src/satomic_swap.rs
> +
Yes, I'll leave comments in the code to remind us about it. However, it is out of scope for now. We will address this issue in a separate PR.

2024-06-12 14:23 UTC, mj-blockydevs commented on README.md
> +sh -c "$(curl -sSfL https://release.solana.com/v1.18.8/install)"
@shamardy Ok, I've updated the README so that it no longer specifies a CLI version. Instead, it now instructs users on how to determine the version on their own.

2024-06-12 14:26 UTC, mj-blockydevs commented on src/utils/payment.rs
> +};
Yes, it will be necessary to support token transfers. This will be implemented later.

2024-06-13 11:39 UTC, shamardy approved these changes
Thanks a lot for the fixes! A few non-blocker comments that should be fixed here before merge.
@laruh can you please check that all your comments are fixed and that you have no more comments.

2024-06-13 11:39 UTC, shamardy commented on Cargo.toml
> +test-bpf = []
test-bpf feature is not used and should be removed
```suggestion
```

2024-06-13 11:39 UTC, shamardy commented on Cargo.toml
> +tokio = { version = "1.36.0", features = ["full"] }
No need for full features for the tests to run
```suggestion
tokio = "1.36.0"
```

2024-06-13 11:39 UTC, shamardy commented on src/instruction.rs
`AtomicSwapInstruction`/`pack`/`unpack` and the error codes are duplicated/used here https://github.com/KomodoPlatform/komodo-defi-framework/pull/2091, I suggest removing them from #2091 once this PR is merged and import them from this repo/crate. Then we would need to edit them only in one place in the future if the need arises.

2024-06-13 11:39 UTC, shamardy commented on src/utils/account.rs
> +    }
Shouldn't this check be placed at the top of the function? If performed before the account creation, the function would return an error, preventing both the account creation and subsequent operations from being executed. This could potentially save computational resources or gas in scenarios where the function fails.

2024-06-13 11:50 UTC, laruh approved these changes
Thanks for the fixes, init v1 LGTM!

2024-06-13 16:03 UTC, mj-blockydevs commented on src/utils/account.rs
> +    }
The invoke_signed function call with the create_account instruction creates a new account and allocates the specified space for it (41 bytes in our case): https://docs.rs/solana-program/latest/solana_program/system_instruction/fn.create_account.html .

Before this instruction is invoked, the vault_pda_data account does not have the allocated space or the necessary initialization, so there is no reason to compare it with anything.

@shamardy Do you want me to put this explanation in the code comment as well?

2024-06-14 12:43 UTC, shamardy approved these changes

2024-06-14 12:49 UTC, merged